2019-01-30 23:34:13,638 ERROR: Exception on /index [GET] [in /Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/burt/PycharmProjects/microblog/app/routes.py", line 51, in index
    form=form, next_url=next_url, prev_url=prev_url)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/burt/PycharmProjects/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/burt/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/burt/PycharmProjects/microblog/app/templates/base.html", line 51, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/burt/PycharmProjects/microblog/app/templates/index.html", line 17, in block "app_content"
    {% include "_post.html" %}
  File "/Users/burt/PycharmProjects/microblog/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" alt="">
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2019-01-30 23:59:35,583 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:77]
2019-01-31 00:02:00,610 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:77]
2019-01-31 08:39:46,597 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:77]
2019-01-31 09:42:43,503 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 09:43:05,279 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 09:44:08,589 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 09:45:26,009 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 10:38:22,598 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 10:38:34,413 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 14:15:09,839 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 16:46:53,553 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:87]
2019-01-31 16:46:59,143 ERROR: Exception on /translate [POST] [in /Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-01-31 19:51:21,984 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 19:51:30,212 ERROR: Exception on /translate [POST] [in /Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-01-31 19:59:06,365 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 19:59:17,994 ERROR: Exception on /translate [POST] [in /Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/Users/burt/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-01-31 20:00:45,754 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:07:31,860 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:08:35,946 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:10:58,086 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:12:31,587 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:14:48,116 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:15:39,334 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:19:14,900 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-01-31 20:21:35,117 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:90]
2019-02-02 22:46:33,226 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:94]
2019-02-02 23:26:28,491 INFO: Microblog startup [in /Users/burt/PycharmProjects/microblog/app/__init__.py:97]
